import Config

# Configure your database
# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
# Binding to loopback ipv4 address prevents access from other machines.
config :bid_match, BidMatch.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "bid_match_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

config :bid_match, BidMatchWeb.Endpoint,
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "ueruWHWDpiO6ChjAlPqv6sCIs45GtDYNH1+cMy5qH7d8mfZ54+7xsqXwCPENnZCx",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:bid_match, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:bid_match, ~w(--watch)]}
  ]

# Watch static and templates for browser reloading.
config :bid_match, BidMatchWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/bid_match_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed

# Enable dev routes for dashboard and mailbox
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
config :bid_match, dev_routes: true

# Do not include metadata nor timestamps in development logs
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
config :logger, :console, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
#
#     https: [
#       port: 4001,
config :phoenix, :plug_init_mode, :runtime

# Set a higher stacktrace during development. Avoid configuring such
#       cipher_suite: :strong,
# in production as building large stacktraces may be expensive.
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
config :phoenix, :stacktrace_depth, 20

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  #
  # If desired, both `http:` and `https:` keys can be
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  # configured to run both http and https servers on
  # different ports.

  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
